export const SITE_CONFIG = {
  name: 'PneuservisVMK',
  title: 'PneuservisVMK Jaroměř | Přezutí, výměna a uskladnění pneumatik',
  description:
    'PneuservisVMK v Jaroměři: přezutí a výměna pneumatik, vyvážení kol, opravy defektů a uskladnění pneu. Náchodská 118, telefon +420 604 355 902.',
  url: 'https://www.pneuservisvmk.cz',
  keywords: [
    'pneuservis',
    'pneuservisvmk',
    'pneuservis vmk',
    'pneuservis jaroměř',
    'pneuservis jaromer',
    'přezutí jaroměř',
    'výměna pneumatik jaroměř',
    'vyvážení kol jaroměř',
    'uskladnění pneu jaroměř',
    'oprava pneumatik jaroměř',
    'pneuservis náchodská',
    'přezutí',
    'výměna pneumatik',
    'vyvážení kol',
    'uskladnění pneu',
    'pneumatiky',
    'zimní pneu',
    'letní pneu',
  ] as string[],
  locale: 'cs_CZ' as const,
  type: 'website' as const,
  logo: '/icon-512.png',
};
